// generated by wsp, DO NOT EDIT.

package main

import "net/http"
import "time"
import "xxx.com/skel/controller/skel"
import "xxx.com/skel/filter"

func init() {
	http.HandleFunc("/skel/add", func(w http.ResponseWriter, r *http.Request) {
		t := time.Now()
		_ = t
		var e interface{}
		c := new(skel.Skel)
		defer func() {
			e = recover()
			if ok := filter.Boss(w, r, map[string]interface{}{"__T__": t, "__C__": c, "__E__": e, "__P__": "/skel/add"}); !ok {
				return
			}
		}()
		c.Add(w, r)
	})

	http.HandleFunc("/skel/del", func(w http.ResponseWriter, r *http.Request) {
		t := time.Now()
		_ = t
		var e interface{}
		c := new(skel.Skel)
		defer func() {
			e = recover()
			if ok := filter.Boss(w, r, map[string]interface{}{"__T__": t, "__C__": c, "__E__": e, "__P__": "/skel/del"}); !ok {
				return
			}
		}()
		c.Del(w, r)
	})

	http.HandleFunc("/skel/get", func(w http.ResponseWriter, r *http.Request) {
		t := time.Now()
		_ = t
		var e interface{}
		c := new(skel.Skel)
		defer func() {
			e = recover()
			if ok := filter.Boss(w, r, map[string]interface{}{"__T__": t, "__C__": c, "__E__": e, "__P__": "/skel/get"}); !ok {
				return
			}
		}()
		c.Get(w, r)
	})

}